server:
  port: 8081

topic:
  send-client: send.client
  send-transaction: send.transaction

spring:
  kafka:
    bootstrap-servers: localhost:29092

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

resttemplate:
  consumer:
    client:
      apihost: http://localhost:8082
